### ISSUE TITLE
Wrong link in debug breadcrumb when using several installations

### ISSUE THREAD

**Issue by nicofrand** [YunoHost-Apps/my_webapp_ynh#10]
I installed the app two times, and when I go in Apps > Custom web app (the second install), the link in the breadcrump points to the first (default) app.

**STR:**

0. Install the app twice, each named "First" and "Second"
0. Go to Apps > Custom web app (the second installation)
0. Click on "Display debug info", which should redirect you to something like https://domain.tld/yunohost/admin/#/apps/my_webapp__2/debug
0. Click in the breadcrumb on "Custom web app" : the link is https://domain.tld/yunohost/admin/#/apps/my_webapp

**What happens:**

* The link is incorrect : `my_webapp` instead of `my_webapp_2`
* Instead of "Custom web app" in the breadcrumb I guess there should be "Second" (the name I gave to my install)

**Comment by tituspijean** [comment]
Does not seem to be the case anymore after the rework of the webadmin. Feel free to reopen if needed.
