### ISSUE TITLE
uploading hugo static website doesn't work

### ISSUE THREAD

**Issue by lucyferu** [YunoHost-Apps/my_webapp_ynh#100]
### Describe the bug

*static website created with Hugo doesn't come up at the domain after directory is transferred in my_webapp.*

### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.1.0.2
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: 1.0

### Steps to reproduce

- *first, i tried the hard way through `scp` and changing owners and permission and anyway nothing worked.*
   
- *then i tried the clearly easier way with filezilla and still not working:*
   1. *install my_webapp'*
   2. *install filezilla*
   3. *connect to server using details received in email and reach `/var/www/my_webapp/www`*
   4. *copy the directory from my laptop in which i built a simple hugo website*
   5. *go to my_webapp domain and see the info+cats page still there.*

-*lastly, i've also just tried [these instructions](https://blog.arkadi.one/p/how-to-use-hugo-with-yunohost/) and they didn't work neither.* 

### Expected behavior

*i would expect to see my static website.*

### Logs

*don't know how to retrieve logs in this case. the only ones i have are [the ones from filezilla](https://vomitb.in/wsdZOObhaK)*

**Comment by alexAubin** [comment]
>static website created with Hugo doesn't come up at the domain after directory is transferred in my_webapp.

What happens then ... if it "doesn't come up", then what comes up ?

**Comment by lucyferu** [comment]
> > static website created with Hugo doesn't come up at the domain after directory is transferred in my_webapp.
> 
> What happens then ... if it "doesn't come up", then what comes up ?

the default my_webapp page with instructions and cats gif.

**Comment by alexAubin** [comment]
Then I guess the `index.html` is still there and was not replaced ... does your hugo generates an index.html ? Did you try removing the default index.html ?

**Comment by lucyferu** [comment]
> Did you try removing the default index.html ?

just tried and i receive this error where try to load the page now:

```

403 Forbidden
nginx

```

**Comment by stilobique** [comment]
Hello,
I make a website with [pelican](https://getpelican.com/), and I have this issue.
However, I have uninstalled this app, and reinstalled-it, and it's solved ; I don't understand.

**Comment by tituspijean** [comment]
What's the output of `ls -la /var/www/my_webapp/www` ? `Error 403` would indicate that the files cannot be read by NGINX as `www-data`.

**Comment by utkarshsethi** [comment]
@lucyferu can you confirm that you only copied the content inside `public` or `www` folder generated by hugo and not the entire directory of your project?

**Comment by tituspijean** [comment]
Last message was a year ago. :)
