### ISSUE TITLE
sshd: unrecognized service

### ISSUE THREAD

**Issue by SylvainCecchetto** [YunoHost-Apps/my_webapp_ynh#11]
Hi,

On a fresh Yunohost install on a Raspberry (with the img file from Yunohost website) my SSH service is "SSH" and not "SSHD".

So I have this error during installation : sshd: unrecognized service

Thanks!

**Comment by SylvainCecchetto** [comment]
Oh sorry, after a new test with moulinette it works ...

**Comment by hferee** [comment]
What do you mean by "after a new test with moulinette"?
I'm in the same configuration as you and can't install this app, with the same error.

**Comment by SylvainCecchetto** [comment]
I mean "by installing directly in the terminal" not with the web administration page.
