### ISSUE TITLE
Multiple platform selection

### ISSUE THREAD

**Issue by eldertek** [YunoHost-Apps/my_webapp_ynh#114]
Let the ability to choose between fiber golang, expressjs etc

**Comment by tituspijean** [comment]
Both mentioned platforms look like they provide their own webserver.

This is currently not in the scope of my_webapp (static and php).

I guess we could provide another option for NGINX `proxy_pass`, or delegate completly the NGINX configuration by relying on #101.

**Comment by eldertek** [comment]
It will be nice if we can have this

**Comment by eldertek** [comment]
At the moment can I create a golang fiber with nginx proxy without making a yunohost app ?
