### ISSUE TITLE
SSH conf & SFTP

### ISSUE THREAD

**Issue by Korbak** [YunoHost-Apps/my_webapp_ynh#13]
[FR]
La page "sécurité" de la doc YunoHost (https://yunohost.org/#/security_fr) propose le changement de port SSH & la limite des users autorisés à la connexion.

Ceci rend incompatible l'affichage final de l'application, qui demande de se connecter avec un user qui n'a pas les droits, à un port qui n'est probablement pas le bon.

Je pense qu'un correctif intéressant pourrait être appliqué de manière à :
- lire le fichier sshd_config
- récupérer les valeurs des utilisateurs autorisés (ou ajouter l'utilisateur webapp1) & du port ssh
- modifier la page index.html en conséquence

With datalove

[EN]
The security page from the YunoHost documentation (https://yunohost.org/#/security) offers to change the SSH port and to limit the access to specific users.

This makes incompatible the final display which asks for connecting with an user who hasn't enough rights, and from a port which is probably not the good one.

I think that an interesting correction could be applyed in order to :
- read the sshd_config file
- get the values of allowed users (or add the allowed user webapp1) & of the ssh port
- consequently edit the page index.html

With datalove

**Comment by tituspijean** [comment]
Most likely fixed by #42.
