### ISSUE TITLE
Restore MyWebApp impossible / mistake in db.sql name

### ISSUE THREAD

**Issue by croulibri** [YunoHost-Apps/my_webapp_ynh#135]
### Describe the bug

Impossible to restore a webapp with a MySQL database

### Context

MyWebApp Version 1.0~ynh15
The webapp to be installed is Piwigo

I thinks this is due to the backup of MyWebApp where we can find in the tar.gz compressed file that the database name includes a * at the end of its name (db.sql* instead of db.sql), making the script unable to find the database.

If I explore the compressed backup file, I find the database name and remove the * at the end of its name, then the restore script works.

(_I have read this advice somewhere without being able to find it again in the forum or in the ticket. So sorry for double posting if this has already been taken into account_)

**Comment by Snapyou2** [comment]
Same problem here, I tried your fix but then the yunohost restore script did not work. It was really messy...

**Comment by grenagit** [comment]
This should be fixed by the latest version #141?

**Comment by OniriCorpe** [comment]
> This should be fixed by the latest version #141?

Yes
