### ISSUE TITLE
Denying dot-files access prevents Let's Encrypt from generating certificates

### ISSUE THREAD

**Issue by kemenaran** [YunoHost-Apps/my_webapp_ynh#2]
The Let's Encrypt Yunohost package (https://github.com/alexAubin/letsencrypt_ynh) currently fails to generate certificates for domains where a `my_webapp` is installed.

This is because, as a part of the certification process, Let's Encrypt needs to access a well-known file (e.g. `http://kemenaran.eu/.well-known/acme-challenge/P7tpoZ2d6mIQZSYtW_SOKRVvunQB-8pDiKJHS5-rIBY`). If dot-files are blocked, this process cannot succeed.

The Let's Encrypt package setups access to the challenge well-known file using an [nginx rule](https://github.com/alexAubin/letsencrypt_ynh/blob/master/conf/nginx.conf). Is there a way to fix this issue, either in `my_webapp` or in `letsencrypt_ynh`?

**Comment by jeromelebleu** [comment]
It should now work, thanks!
