### ISSUE TITLE
How to activate PHP modules

### ISSUE THREAD

**Issue by gryckelynck** [YunoHost-Apps/my_webapp_ynh#22]
I'd like to activate sqlite driver.
Is it possible?
How to access to php.ini to do this, please?

**Comment by Thatoo** [comment]
How could I install and use these following modules php-curl php-gd php-mysql ?

**Comment by ericgaspar** [comment]
try `sudo apt  install php8.0-curl php8.0-gd php8.0-mysql php8.0-mbstring`
replace whith the PHP version you want

**Comment by Thatoo** [comment]
`php7.3-curl php7.3-gd php7.3-mysql php7.3-mbstring` are already installed but when I go to the webapp page, I get this error : 
Fatal error: Uncaught Error: Class 'mysqli' not found in

**Comment by ericgaspar** [comment]
What about installing `php7.3-mysqli`

**Comment by Thatoo** [comment]
php7.3-mysqli doesn't exist, I believe it is included in php7.3-mysql. I guess something need to be set in php.ini

**Comment by Thatoo** [comment]
I uninstall custom webapp and reinstall and it seems to work now
