### ISSUE TITLE
Nom de la base de donnée

### ISSUE THREAD

**Issue by krickmanivelle** [YunoHost-Apps/my_webapp_ynh#24]
La presence du caractère "_" entraine un bug lors de l'installation de certaine application qui liste les bases disponibles, la suppression du caractère dans manifest.json règle le problème.

**Comment by tituspijean** [comment]
Cela sonne plutôt comme un mauvais code dans l'application qu'un problème avec l'app. `_` est un caractère assez courant.

Désolé pour le retard, et tout ça pour fermer... n'hésite pas à préciser quelles apps bug à cause de ça.
