### ISSUE TITLE
Ecrasement de config en multi-install lors de l'upgrade

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost-Apps/my_webapp_ynh#27]
Hello,

Lors de l'upgrade de cette app par l'interface admin web de yunohost, je crois qu'une partie de la config a été écrasée, sur Raspbian Jessie.
J'avais deux my_webapp_ynh avec SFTP, mais seule une était indiquée comme "à mettre à jour". Une fois l'upgrade faite, la config de l'accès SFTP (la partie "##-> my_webapp..." dans /etc/ssh/sshd_config) pour la deuxième app a disparu. Du coup impossible de m'y connecter sans recopier la config à la main. Le site est cependant toujours servi par Nginx.

Y'a-t-il qqchose à réparer ? Je reste disponible pour aider au fix.

Merci !

**Comment by tituspijean** [comment]
A priori le nouveau système de permissions/SSH évite ce problème. A réouvrir si tu remarques encore ce comportement.
