### ISSUE TITLE
no contact

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/my_webapp_ynh#29]
the Custom Webapp is installed but the Contact to the server does NOT work.  Have a lock at the log
Any idea what could help? thanks

> WinSCP Version 5.13.7
> 
> Session name: webapp1@ xx.yy.de (Site)
> . 2019-01-09 16:28:34.413 Host name: xx.yy.de (Port: 22)
> . 2019-01-09 16:28:34.413 User name: webapp1 (Password: No, Key file: No, Passphrase: No)
> . 2019-01-09 16:28:34.413 Tunnel: No
> . 2019-01-09 16:28:34.413 Transfer Protocol: SFTP (SCP)
> . 2019-01-09 16:28:34.413 Ping type: Off, Ping interval: 30 sec; Timeout: 15 sec
> . 2019-01-09 16:28:34.413 Disable Nagle: No
> . 2019-01-09 16:28:34.413 Proxy: None
> . 2019-01-09 16:28:34.413 Send buffer: 262144
> . 2019-01-09 16:28:34.413 SSH protocol version: 2; Compression: No
> . 2019-01-09 16:28:34.413 Bypass authentication: No
> . 2019-01-09 16:28:34.413 Try agent: Yes; Agent forwarding: No; TIS/CryptoCard: No; KI: Yes; GSSAPI: Yes
> . 2019-01-09 16:28:34.413 GSSAPI: Forwarding: No; Libs: gssapi32,sspi,custom; Custom: 
> . 2019-01-09 16:28:34.413 Ciphers: aes,chacha20,blowfish,3des,WARN,arcfour,des; Ssh2DES: No
> . 2019-01-09 16:28:34.413 KEX: ecdh,dh-gex-sha1,dh-group14-sha1,rsa,WARN,dh-group1-sha1
> . 2019-01-09 16:28:34.413 SSH Bugs: Auto,Auto,Auto,Auto,Auto,Auto,Auto,Auto,Auto,Auto,Auto,Auto,Auto
> . 2019-01-09 16:28:34.413 Simple channel: Yes
> . 2019-01-09 16:28:34.413 Return code variable: Autodetect; Lookup user groups: Auto
> . 2019-01-09 16:28:34.413 Shell: default
> . 2019-01-09 16:28:34.413 EOL: LF, UTF: Auto
> . 2019-01-09 16:28:34.413 Clear aliases: Yes, Unset nat.vars: Yes, Resolve symlinks: Yes; Follow directory symlinks: No
> . 2019-01-09 16:28:34.413 LS: ls -la, Ign LS warn: Yes, Scp1 Comp: No
> . 2019-01-09 16:28:34.413 SFTP Bugs: Auto,Auto
> . 2019-01-09 16:28:34.413 SFTP Server: default
> . 2019-01-09 16:28:34.413 Local directory: default, Remote directory: home, Update: Yes, Cache: Yes
> . 2019-01-09 16:28:34.413 Cache directory changes: Yes, Permanent: Yes
> . 2019-01-09 16:28:34.413 Recycle bin: Delete to: No, Overwritten to: No, Bin path: 
> . 2019-01-09 16:28:34.413 DST mode: Unix
> . 2019-01-09 16:28:34.413 --------------------------------------------------------------------------
> . 2019-01-09 16:28:34.440 Looking up host "xx.yy.de" for SSH connection
> . 2019-01-09 16:28:34.441 Connecting to 78.48.35.251 port 22
> . 2019-01-09 16:28:34.527 We claim version: SSH-2.0-WinSCP_release_5.13.7
> . 2019-01-09 16:28:34.547 Waiting for the server to continue with the initialization
> . 2019-01-09 16:28:34.547 Detected network event
> . 2019-01-09 16:28:34.593 Detected network event
> . 2019-01-09 16:28:34.593 Server version: SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u4
> . 2019-01-09 16:28:34.593 Using SSH protocol version 2
> . 2019-01-09 16:28:34.593 Have a known host key of type ssh-ed25519
> . 2019-01-09 16:28:34.593 Waiting for the server to continue with the initialization
> . 2019-01-09 16:28:34.604 Detected network event
> . 2019-01-09 16:28:34.605 Doing ECDH key exchange with curve Curve25519 and hash SHA-256
> . 2019-01-09 16:28:34.620 Waiting for the server to continue with the initialization
> . 2019-01-09 16:28:34.678 Detected network event
> . 2019-01-09 16:28:35.222 Server also has ecdsa-sha2-nistp256/ssh-rsa host keys, but we don't know any of them
> . 2019-01-09 16:28:35.225 Host key fingerprint is:
> . 2019-01-09 16:28:35.225 ssh-ed25519 256 e9:af:11:43:44:2d:55:37:34:d0:7a:f7:d4:2c:2f:53 hZ4eIwOtMU8bRkywQqxPrtBNsV4ie5tV2oL4M5aZIEY=
> . 2019-01-09 16:28:35.225 Verifying host key ssh-ed25519 0x72b7fd6bb3eb8b1c c00dde4370b06af9 714cf0ead7468d7d 9452e19702207184 ,0x1a37e0efe551d33e 38f53514299c49e4 c11a91c7587a4f45 c4675852286eaa74  with fingerprints ssh-ed25519 256 e9:af:11:43:44:2d:55:37:34:d0:7a:f7:d4:2c:2f:53 hZ4eIwOtMU8bRkywQqxPrtBNsV4ie5tV2oL4M5aZIEY=
> . 2019-01-09 16:28:35.259 Host key matches cached key
> . 2019-01-09 16:28:35.260 Initialised AES-256 SDCTR client->server encryption
> . 2019-01-09 16:28:35.260 Initialised HMAC-SHA-256 client->server MAC algorithm
> . 2019-01-09 16:28:35.260 Initialised AES-256 SDCTR server->client encryption
> . 2019-01-09 16:28:35.260 Initialised HMAC-SHA-256 server->client MAC algorithm
> . 2019-01-09 16:28:35.260 Waiting for the server to continue with the initialization
> . 2019-01-09 16:28:35.261 Detected network event
> ! 2019-01-09 16:28:35.261 Using username "webapp1".
> . 2019-01-09 16:28:35.272 Waiting for the server to continue with the initialization
> . 2019-01-09 16:28:35.286 Detected network event
> . 2019-01-09 16:28:35.286 Server offered these authentication methods: publickey,password
> . 2019-01-09 16:28:35.286 Prompt (password, "SSH password", <no instructions>, "&Passwort:")
> . 2019-01-09 16:28:41.156 Sent password
> . 2019-01-09 16:28:41.156 Waiting for the server to continue with the initialization
> . 2019-01-09 16:28:41.322 Detected network event
> . 2019-01-09 16:28:41.322 Access granted
> . 2019-01-09 16:28:41.322 Opening session as main channel
> . 2019-01-09 16:28:41.322 Waiting for the server to continue with the initialization
> . 2019-01-09 16:28:42.044 Detected network event
> . 2019-01-09 16:28:42.044 Network error: Software caused connection abort
> * 2019-01-09 16:28:42.065 (EFatal) Netzwerkfehler: Software verursachte einen Verbindungsabbruch.
> * 2019-01-09 16:28:42.065 Anmeldungsprotokoll (Siehe Sitzungsprotokoll für Details):
> * 2019-01-09 16:28:42.065 Verwende Benutzername "webapp1".
> * 2019-01-09 16:28:42.065 
> * 2019-01-09 16:28:42.065 Anmeldung fehlgeschlagen.

**Comment by anmol26s** [comment]
1. Use FileZilla
2. If you change the port number for ssh then change it in Port for Filezilla
3. The option should be SFTP

It should work then if ssh is working correctly.

**Comment by rocky-III** [comment]
ok now i use FileZilla

for port 22    I get the Error  "Connection rest by peer"

I opened up port 200 in the Router and in the YunoHost Firewall - 
and chose it in FileZilla - now I I get "Connection refused"

any Idea? thanks

**Comment by rocky-III** [comment]
I added „PasswordAuthentication yes“ to /etc/ssh/sshd_config      
now i got the error message „Authentication missing“

so I tried  „root“ instead of „webapp1“ as username and was able to log in !!! Whhooooo

Somehow  the username and password management of my Yunohost Server  (CubieTruck image) is not working right
