### ISSUE TITLE
Installation failed when dash in the password

### ISSUE THREAD

**Issue by jbinard** [YunoHost-Apps/my_webapp_ynh#3]
When you try to install the app with a password containing one (or more) dash, the installation failed with the following error:

```
yunohost app setting: error: 
 -v/--value: expected one argument
usage: yunohost app setting [-h] [-d] [-v VALUE] app key
+ sudo yunohost app setting my_webapp password -v -test- --quiet
+ ynh_app_setting_set my_webapp password -test-
```

**Comment by Psycojoker** [comment]
Issue migrated at https://dev.yunohost.org/issues/485

It would be great if you could use this bugtracker instead of github from now one :) (you don't have to create an account and you can log with github)
