### ISSUE TITLE
Tomcat7 project under my_webapp 403 forbidden

### ISSUE THREAD

**Issue by elfefe** [YunoHost-Apps/my_webapp_ynh#33]
Hello,

I installed a tomcat7 server under my_webapp, i configured nginx but i still have this 403 forbidden Error. 

> nano /etc/nginx/sites-availabe/AppTek

```
server {
        listen 80 ;

        root /var/www/my_webapp/www/webapps;

        index index.html index.htm index.nginx-debian.html index.php index.jsp;

        server_name webapps;
}
```

It's linked in site-enable and i did 

> sudo chown -R www-data:www-data webapps

Sure nginx is reloaded and tomcat started.

Do you have any idea ?

**Comment by tituspijean** [comment]
Sorry for the late answer. If you still have the issue, please share the actual NGINX config for the app (`/etc/nginx/conf.d/DOMAIN.TLD.d/my_webapp.conf`). You should not write your own `server` block like that.
