### ISSUE TITLE
Problème après mise à jour de Custom Webapp

### ISSUE THREAD

**Issue by arnauldb** [YunoHost-Apps/my_webapp_ynh#37]
Bonjour,

après avoir fait la mise à jour proposée par Yunohost de Custom Webapp , mise à jour effectuée hier ou avant hier je ne sais plus, un problème survient.

En effet, j’ai un site internet statique construit avec Hugo https://gohugo.io/ . Je mets donc simplement mes fichiers dans l’application Custom Webapp.

Or la mise à jour de Custom Webapp a cassé mon site (Il est entendu que je n’ai pas modifié mon site entre-temps).

Le site avant la mise à jour :

![](https://framapic.org/h8RAZF9jvsaA/TyBGPuktJPr9)

Le site après la mise à jour :

![](https://framapic.org/u3YKlcRC3XUP/ut5JgikEhjV7)

J’ai donc tenté une restauration de Custom Webapp d’avant la mise à jour et mon site est revenu à la normale.

**Comment by tituspijean** [comment]
N'hésite pas à réouvrir en montrant la config NGINX avant/après la mise à jour. Il est probable que cela recommence avec la mise à jour sortie aujourd'hui.
