### ISSUE TITLE
Custom Web Application password issue

### ISSUE THREAD

**Issue by ralphshinevar** [YunoHost-Apps/my_webapp_ynh#41]
I installed the Gibbon LMS in Yunohost using the custom web app.  When I try to logon into Gibbon, it defaults back to YunoHost Portal.  What can I do to get access?  I've tried YunoHost accounts as well as the user webapp6 which appeared at the install in YunoHost.

**Comment by tituspijean** [comment]
It may be due to a bad redirect if Gibbon LMS does not know its own, actual, URL.
Feel free to reopen with a screenshot:
1. open the page
2. open your browser's debugger (F12, Network tab)
3. try to log in
