### ISSUE TITLE
webapp1 as user after 1.0~ynh3 upgrade

### ISSUE THREAD

**Issue by ericgaspar** [YunoHost-Apps/my_webapp_ynh#49]
After the 1.0~ynh3 upgrade, the credentials page still displays **webapp1** as user instead of **my_webapp**

**Comment by alexAubin** [comment]
that's probably because you still have the index.html which is not regenerated during the upgrade because it's supposed to be overwritten by the user ...?

**Comment by ericgaspar** [comment]
oh yes, you're right. closing this issue.
