### ISSUE TITLE
YoloMerge provoked a permission error

### ISSUE THREAD

**Issue by Jaxom99** [YunoHost-Apps/my_webapp_ynh#50]
Hi there,

I installed a php app (InvoicePlane) inside a webapp some time ago. Recently, stuff broke (no pdf generation available via php) and displayed message of wrong permissions.
After some debug and looking into php config files of Yunohost, it looks like the user/group was changed from webapp1 to my_webapp in ths commit (https://github.com/YunoHost-Apps/my_webapp_ynh/commit/66cc5be9f8a41090ad38d71032ec7ec6ec366330) (with a really obvious commit message :stuck_out_tongue_closed_eyes: ) but the config in my host did not change. 

Doing a manual `chmod` in the `/var/www/my_webapp` folder fixed it !

So, maybe this issue will help some folk around here :smile_cat:

**Comment by alexAubin** [comment]
Indeed what happens in the upgrade script wasnt consistent with the install script, should be fixed now

**Comment by b4D8** [comment]
It seems that I have the same issue here.
I encounter a permission error while logging with `webapp1`, `my_webapp` or `admin`.

Doing a `cd /var/www` and `ls -la` shows that all my webapps now have the following permissions: 

```
drwxr-xr-x  3 root      root      4096 May 26 15:10 my_webapp
drwxr-xr-x  3 root      root      4096 May 26 17:37 my_webapp__2
drwxr-xr-x  3 root      root      4096 May 26 17:40 my_webapp__3
drwxr-xr-x  3 root      root      4096 Jun  4 21:32 my_webapp__4
...
```

What's the right way to `chmod` the directories?

Thanks for your help!
