### ISSUE TITLE
Possibilité de configurer la BDD

### ISSUE THREAD

**Issue by menestrwell** [YunoHost-Apps/my_webapp_ynh#53]
Bonjour, 
En tant qu'utilisateur de Yunohost, je souhaite pouvoir paramétrer la création de la base de données à l'installation du composant Custom_Webapp.

db_name
user
password

**Comment by tituspijean** [comment]
Tu peux "tricher" en clonant le repo et modifiant ce fichier:

https://github.com/YunoHost-Apps/my_webapp_ynh/blob/testing/scripts/install#L81-L83

```
git clone https://github.com/YunoHost-Apps/my_webapp_ynh
cd my_webapp
nano +81 script/install
```

Modifie ces lignes ainsi:
```
db_name=TON_DB_NAME
db_pwd=TON_DB_PWD
ynh_app_setting_set --app=$app --key=db_name --value=$db_name
ynh_mysql_setup_db --db_user=$db_name --db_name=$db_name --db_pwd=$db_pwd
```
et installe l'app: `yunohost app install . --force`

**Comment by menestrwell** [comment]
Ok merci pour ce retour :)

**Comment by tituspijean** [comment]
(et désolé pour la réponse très tardive ^^)
