### ISSUE TITLE
Gestion des redirections internes (HTACCESS)

### ISSUE THREAD

**Issue by menestrwell** [YunoHost-Apps/my_webapp_ynh#54]
Bonjour, 
J'ai pour projet un petit site en React (Client side only)
Je l'hébergeait avant sur un autre serveur et avait mis en place un .htaccess pour rediriger les routes incomprises vers l'index de l'application et ainsi éviter les 404.
Est il possible de faire de même avec Custom Webapp ?

**Comment by ericgaspar** [comment]
YunoHost being based on NGINX you will have to convert the .htaccess into NGINX rules in you my_webapp NGINX config.
This htaccess to NGINX converter can help you...
https://winginx.com/en/htaccess

**Comment by menestrwell** [comment]
ok thank you :+1:
