### ISSUE TITLE
Possibilité d'authentifier une partie du site 

### ISSUE THREAD

**Issue by michelwend** [YunoHost-Apps/my_webapp_ynh#56]
Bonjour,
Suite à cette discussion sur le forum:
https://forum.yunohost.org/t/proteger-acces-repertoire-web-htaccess-pour-my-webapp-sous-nginx/13911/15
est-il envisageable d'inclure une authentification de la connexion pour certains répertoires du site?
En vous remerciant

**Comment by alexAubin** [comment]
Probablement oui mais je ne sais pas quoi te dire ... à mon avis on ne peut pas spécialement intégrer quoi que ce soit dans l'app directement car ce n'est pas trivial (on ne sais pas à l'avance quel chemin administrateur souhaite protéger)

Pour ton erreur de syntaxe dans ton post sur le forum, difficile de t'aider sans avoir le contenu exact du fichier ... tu as tenté de le poster dans le post précédent, mais la syntaxe est toute cassée car tu t'es probablement enmélé les pinceaux dans la syntaxe markdown etc ... Le plus simple serait de partager le contenu du fichier avec par exemple https://paste.yunohost.org/

**Comment by michelwend** [comment]
Merci en tout cas pour votre réponse, j'ai déposé ma demande à la suite du forum en utilisant [https://paste.yunohost.org/](https://paste.yunohost.org/)
