### ISSUE TITLE
Pas de chroot sftp ?

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/my_webapp_ynh#6]
https://forum.yunohost.org/t/mywebapp-sft-et-chroot/2410

**Comment by anmol26s** [comment]
I cannot access the webapp through  sftp .
I have enabled only key authentication in ssh and use different port to connect through ssh

**Comment by anmol26s** [comment]
It was because I had disabled password access. It can be solved by only giving access through password for webapp users.

**Comment by tituspijean** [comment]
Users are now chroot-ed, per the new sshd config. Connection is made with the password set during installation.

Feel free to reopen if that is not the case on your end.
