### ISSUE TITLE
Error 403 on RPi 3B with YunoHost 4.2.3.1 (testing)

### ISSUE THREAD

**Issue by pp-r** [YunoHost-Apps/my_webapp_ynh#63]
Hello,

Following this post on the forum ...
https://forum.yunohost.org/t/fonctionnement-de-filezilla-et-customwebapp-depuis-une-mise-a-jour/15600/8
... I tried to make a fresh install of the application on my Raspberry Pi 3 B which runs with the latest testing version of YunoHost.

Unfortunately I get a 403 error and sftp access via FileZilla is impossible: Authentication failed.

With FileZilla as admin I have :
- 755 on /var/www/my_webapp ;
- 755 on /var/www/my_webapp/www ;
- 640 on /var/www/my_webapp/www/index.html.

It works both -web and sftp- on my VPS x64 with the last stable YunoHost release 4.1.8.
And I've :
- 755 on /var/www/my_webapp ;
- 755 on /var/www/my_webapp/www ;
- 644 on /var/www/my_webapp/www/index.html.

I hope that these lines will help to solve the issue <3

ppr

**Comment by sy6sy2** [comment]
Same issue after upgrading to Yunohost 4.2, I get a 403 after a fresh install of my_webapp.

Chmod index.html to 644 fix the issue.
