### ISSUE TITLE
update to php 7.3

### ISSUE THREAD

**Issue by Thatoo** [YunoHost-Apps/my_webapp_ynh#66]
Last update of my webapp didn't update the nginx conf files so fastcgi_pass remained to php7.0-fpm-my_webapp.sock

`        fastcgi_pass unix:/var/run/php/php7.0-fpm-my_webapp.sock;`

I only needed to change the 0 into 3 to make my webapp work again.
`        fastcgi_pass unix:/var/run/php/php7.3-fpm-my_webapp__2.sock;`

I guess it would be better to make the change automatically during next update.

**Comment by alexAubin** [comment]
This should already be the case ...

Could it be that you told the app to not update the nginx conf using the experimental config panel ?

Also sharing the upgrade logs would help ...

**Comment by Thatoo** [comment]
Good to know.

I don't remember veer used the the experimental config panel but I'll check that. I'll share the logs too as soon as borg has finished... I rebooted the server before finding the solution and when I reboot, borg starts and it takes a little bit of time before I can do anything.

**Comment by Thatoo** [comment]
In the experimental config panel (I'm almost sure I've never been there, I had to read https://forum.yunohost.org/t/accessing-the-experimental-config-panel/11844 to find out how to go there), I have

Overwriting config files
Overwrite the NGINX config file?
No
If the file is overwritten, a backup will be created.

Should I put yes then?
Should I verify that it's "yes" on other apps too?

Here are my_webapp update logs : https://paste.yunohost.org/raw/oyonamofis

**Comment by Thatoo** [comment]
Well, if I trigger the answer button to yes about "Overwrite the NGINX config file?", then I can't click on the save button at the botton so I basically can't change this option...

**Comment by alexAubin** [comment]
Hmpf I can't believe this option is at false by default ... what the fuck ...

As a workaround, you can `nano /etc/yunohost/apps/my_webapp/settings.yml` and set "1" after `overwrite_nginx:`

**Comment by Thatoo** [comment]
Well, if I trigger the answer button to yes about "Overwrite the NGINX config file?", then I can't click on the save button at the botton so I basically can't change this option...
