### ISSUE TITLE
Possibilité de choisir la version de PHP

### ISSUE THREAD

**Issue by ceeddd** [YunoHost-Apps/my_webapp_ynh#69]
Bonjour, 

Serait-il possible d'envisager la possibilité de choisir la version de PHP lors de l'installation, parmi les versions disponibles sur le système ? 

En effet j'aurais souhaité installer deux fois my_webapp, chacun avec une version differente de php en fonction des applications php.

Versions utilisées : 
Yunohost : 4.2.8.3
my_webapp : 1.0~ynh5

Merci

**Comment by ericgaspar** [comment]
Here is branch with PHP 7.3, 7.4 and 8.0 to choose from at install... This needs to be tested.
`sudo yunohost app install https://github.com/YunoHost-Apps/my_webapp_ynh/tree/php-custom`

**Comment by ericgaspar** [comment]
Ok, thanks for trying! I made some changes, do you mind testing again?

**Comment by ceeddd** [comment]
Thanks.I tried again, same result.

**Comment by ericgaspar** [comment]
mmh. Ok ready for a last try?

**Comment by ceeddd** [comment]
Sure. I have this time a "502 Bad Gateway" from nginx with .php files. 
.html files are ok.

**Comment by tituspijean** [comment]
Now it should work. 😇

**Comment by ceeddd** [comment]
It works !

**Comment by cloo** [comment]
It did not work for me..
https://paste.yunohost.org/raw/gicociweta

**Comment by tituspijean** [comment]
Thank you for your feedback! Indeed, the way PHP version are installed changed in YunoHost 4.3.3 and this PR was not updated accordingly. Hopefully my commits will fix that.
