### ISSUE TITLE
sftp connection does not work with user created by app

### ISSUE THREAD

**Issue by vivienkit** [YunoHost-Apps/my_webapp_ynh#7]
Hi !
I've got an issue with sftp connection as reported here (in french) : https://forum.yunohost.org/t/connexion-sftp-impossible/1160/9
Could I have some help on this please ? 
Thanks !

**Comment by anmol26s** [comment]
Have disabled the password access through ssh?

**Comment by vivienkit** [comment]
Well, no. I haven't looked at this issue for a while and it actually works now :-/ so I guess something has been corrected since then...
Thanks anyway for trying to help @anmol26s !
