### ISSUE TITLE
Config unavailable. Error: "Config panel versions '0.1' are not supported."

### ISSUE THREAD

**Issue by cloo** [YunoHost-Apps/my_webapp_ynh#72]
### Describe the bug

Choosing"Configure this app" gives an error: Config panel versions '0.1' are not supported.

### Context

- Hardware: *Old laptop or computer*
- YunoHost version: *4.3.2.2 (stable)*
- I have access to my server: *all kinds of access*. Using web UI in this case.
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: *1.0~ynh5*
 
### Steps to reproduce

 - *If the error occurs in your browser, explain what you did:*
   1. *Go to ' Applications
my_webapp '*
   2. *Click on 'Configure this app'*
   3. *See error: Config panel versions '0.1' are not supported.*

### Expected behavior

Configuration options for my_webapp should be displayed.

### Logs

Tools>Logs list does not contain this event.
 

![211114-214920](https://user-images.githubusercontent.com/651760/141696884-c5e2744b-e05a-46f8-8c51-cf0de5a09517.png)

**Comment by verstecken** [comment]
Same Issue!

**Comment by ericgaspar** [comment]
This is still the old config_panel settings...

**Comment by verstecken** [comment]
means, to be ignored? don‘t understand the answer. Or is there a way to fix it and see the configuration panel?

**Comment by ericgaspar** [comment]
my_webapp configuration panel was already implemented with a beta version 0.1. This beta version was not activated by default.
Since, Config Panels has been completely rewiten and is now at version 1.0. The error you are getting is from the old version and means that the my_webapp Config panel hasn't yet been adapted to the new standard.

**Comment by fbeauvais** [comment]
Same same here

**Comment by alexAubin** [comment]
Fixed by https://github.com/YunoHost-Apps/my_webapp_ynh/pull/82
