### ISSUE TITLE
Error 404, static website

### ISSUE THREAD

**Issue by Sysdraw** [YunoHost-Apps/my_webapp_ynh#75]
Hello,

I have a website static in ReactJS, but when I try to go in the path https://foo.fr/test I have a redirection 404 of Nginx.

I think the configuration isn't good for modern framework as ReactJS, Angular, VueJS and more...

**Comment by tituspijean** [comment]
Per discussion over at #76, this is too specific to the chosen framework. Thanks for trying it out though!

**Comment by NathanRussellUK** [comment]
I don't think this is a framework specific feature / issue, see discussion 😄 :
https://github.com/YunoHost-Apps/my_webapp_ynh/pull/76#issuecomment-1168559495
