### ISSUE TITLE
#4 - systemctl reload sshd doesn't work either

### ISSUE THREAD

**Issue by bencharp** [YunoHost-Apps/my_webapp_ynh#8]
For me, neither `service sshd reload` nor` systemctl reload sshd` work. => #4 

```
sudo service sshd reload
sshd: unrecognized service
```

```
sudo systemctl reload sshd
Failed to reload sshd.service: Unit sshd.service failed to load: No such file or directory.
```
Why not use `service ssh reload` instead => [https://wiki.debian.org/fr/SSH#line-352](https://wiki.debian.org/fr/SSH#line-352) ?

**Comment by JimboJoe** [comment]
@bencharp does `systemctl reload ssh` work on your side?
Using systemd syntax would be better, because the `service` sysVinit syntax will become obsolete at some point.

**Comment by bencharp** [comment]
@JimboJoe `systemctl reload ssh` works right on my side. 
If it's better…
