### ISSUE TITLE
Change PHP version under 7.1

### ISSUE THREAD

**Issue by Dr-Wily** [YunoHost-Apps/my_webapp_ynh#92]
Hello,
How can I change PHP version under 7.1 ? I want to use PHP5.
How to use PHP5 in my webapp ?

Thanks

**Comment by tituspijean** [comment]
Hello,

[PHP7.1 has been deprecated almost three years ago, and PHP5 almost four years ago.](https://www.php.net/eol.php) We will most likely not support installing them on your server, sorry. The page I linked has guides for your to upgrade your code up to PHP8.

What do you think, @YunoHost-Apps/apps-group, though?

**Comment by Dr-Wily** [comment]
I have some website (not publicy exposed) who wor only with old versions of PHP. I can't upgrade the because I'am not the dev of these app. This is statistics app and (PHPmyVisit) and the developer won't develop a tools to migrate database to piwik and /or to matomo.

I don't want to lost 14 years of stats just because it's impossible to keep this app working. At this time I must keep a Debian 5 server just for this app.

Docker is a solution but it don't work well with yunohost and my last solution is mywebapp but again no php5... it's hopeless...

**Comment by ericgaspar** [comment]
You can fork mywebapp_ynh and add PHP5 to the `manifeste.json`

https://github.com/YunoHost-Apps/my_webapp_ynh/blob/ec83a54c90aaad5ea80c8558939fdd0f3b080b5d/manifest.json#L67
