### ISSUE TITLE
avoid nuking existing nginx configs on update

### ISSUE THREAD

**Issue by mooseyboots** [YunoHost-Apps/my_webapp_ynh#93]
### Describe the bug

on updating an instance of my_webapp, existing nginx config is backed up and a new one put in its place. i wonder if this makes sense in the case of such an app, which will almost always require substantial user edits to its nginx config to run the app it contains. is there no way around it? merging the changes back in by hand seems pretty fiddly and error-prone. are the changes to the nginx config in a new version ever significant themselves? if not, is it possible to check whether there are any significant changes and only push the existing config aside if there are?

ideally a diff/merge would be possible.

### Context

- Hardware: Other ARM board 
- YunoHost version: 11.x (stable)
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

- Using, or trying to install package version/branch: 1.0~ynh10

### Steps to reproduce

upgrade from ~ynh9 to ~ynh10

**Comment by tituspijean** [comment]
Hi @mooseyboots, thanks for the feedback! We will re-implement this feature in the version after the one we just released. So if you want to avoid re-writing your configs again, avoid to upgrade to v~ynh11. ;)

**Comment by tituspijean** [comment]
You might also have a look [the hooks system](https://yunohost.org/en/packaging_apps_hooks#post-app-upgrade) in our documentation. With these you can implement a basic bash script that will re-override the NGINX config after an upgrade.
