### ISSUE TITLE
Site non consultable par le public

### ISSUE THREAD

**Issue by thsfo** [YunoHost-Apps/my_webapp_ynh#95]
Bonjour,

J'ignore pourquoi bien tout fonctionne très bien, j'ai installé un joomla grâce my-webapp, ça fonctionne très bien sauf que les visiteurs public n'accède pas au site et on arrive sur une page de connexion yunohost. Comment faire ?

I don't know why ... everything works very well, I installed a joomla thanks to my-webapp, it works very well except that public visitors do not access the site and you arrive on a yunohost login page. How to do ?

thanks you for your help !

**Comment by tituspijean** [comment]
Have you given Visitors access to the app, in the permissions panel of the webadmin?

**Comment by thsfo** [comment]
Yes, but for example on mobile device with android to a friend, it display yunohost panel, but outside it's ok. I don't understand !

**Comment by tituspijean** [comment]
> it works very well except that public visitors do not access the site and you arrive on a yunohost login pag

> for example on mobile device with android to a friend, it display yunohost panel, but outside it's ok

I really do not understand your issue. These look like opposite statements. Please clarify.
Share also the NGINX logs showing any redirection that the visitors trigger.

**Comment by tituspijean** [comment]
Closing as stale issue.
