### ISSUE TITLE
Can't edit index.html at all without encountering a 403 Forbidden message

### ISSUE THREAD

**Issue by Wave6677** [YunoHost-Apps/my_webapp_ynh#96]
On a fresh install of my_webapp, using sftp with the my_webapp user to edit or replace the index.html file at all causes a "403 Forbidden" error.

- Hardware: x86_64 Desktop PC
- YunoHost version: 11.0.9.15
- I have access to my server: Direct Access, SSH, SFTP, WebAdmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: No
- Using, or trying to install package version/branch: main

### Steps to reproduce
1. Install my_webapp
2. Use SFTP to log into my_webapp using the webapp password
3. Edit/Replace index.html
4. Visit the webapp from a browser
5. "403 Forbidden"
### Expected behavior

After editing Index.html, have it update

### Logs

Not really sure if there are logs for a file change. I can attach a screenshot of the 403 error but its fairly common and unhelpful. If there's anything in particular I should run in the terminal or logs I can find and post please let me know.

### Update
I fixed the issue by running 
***cd /var/www/my_webapp/www
chown 997:33 index.html***
as the root user. I don't think that is supposed to be normal however.

**Comment by Wave6677** [comment]
> 

id 997 outputs:
```uid=997(nextcloud) gid=997(nextcloud) groups=997(nextcloud, 1002(multimedia)```
id 33 gives
```uid=33(www-data) gid=33(www-data) groups=33(www-data)```
and ls -la /var/www/my_webapp/www shows
```
total 32
drwxr-xr-x  2 my_webapp www-data  4096 Oct 18 01:58 .
drwxr-x---+ 3 root      root      4096 Oct 18 01:10 ..
-rw-r--r--  1 my_webapp my_webapp 2750 Sep 25 00:32 newfile.html
-rw-r--r--  1 my_webapp my_webapp 2750 Sep 25 00:32 newfile2.html
-rw-r-----  1 my_webapp my_webapp 2750 Sep 25 03:38 index.html
-rw-r--r--  1 my_webapp my_webapp 2750 Sep 25 00:32 newfile3.html
-rw-r--r--  1 my_webapp my_webapp 1232 Sep 25 00:24 newfile.js
-rw-r--r--  1 my_webapp my_webapp 3161 Jan 15  2022 newfile.css
```

**Comment by tituspijean** [comment]
OK, got it. The actual issue is that your `index.html` is somehow not belonging to ``www-data` not readable by `other` users: `-rw-r-----`, hence your need to `chown`.
You need to be careful about it when replacing files through SFTP. A brand new app would have these permissions:

`-rw-r----- 1 my_webapp www-data 1.1K Oct 18 08:12 index.html`

If you want to fix it without too much hassle, force-upgrade the app: `yunohost app upgrade my_webapp -F`

**Comment by Wave6677** [comment]
Alright, I appreciate the help. I'm not sure why the permissions don't transfer correctly but the issue has a solution so I will not complain or take up any more of your time lol
Thank you!
